<a href="https://colab.research.google.com/github/ganesh12112/ganesh12112/blob/main/AI_and_ML_assignment_1(NumPy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#assignment on machine learning libraries
# assignments on numpy
# 1.get the max value from matrix
# Syntax : matrix.max()
# return max value from given matrix
# example 1:
import numpy as np
gf = np.matrix('[54, 1; 12, 3]')
max = gf.max()
print(max)

54


In [ ]:
# example 2
import numpy as np
gf = np.matrix('[1,2,3; 4,5,6;7,8,9]')
max = gf.max()
print(max)

9


In [ ]:
# get the minnimum value of matrix
# example 1
import numpy as np
# make matrix with numpy
gf = np.matrix('[32,45;56,78]')
min = gf.min()
print(min)

32


In [ ]:
# Find the number of rows and columns of a given matrix using NumPy
# eaxmple 1:using the .shape Attribute
import numpy as np
matrix = np.array([[9,9,9],[8,8,8]])
dimensions = np.shape(matrix)
rows , columns = dimensions
print("rows:",rows)
print("columns:",columns)

rows: 2
columns: 3


In [ ]:
# numpy.reshape() to find number of rows and columns of a matrix
import numpy as np
matrix = np.arange(1,10).reshape((3,3))
# original matrix
print(matrix)
# Number of rows and columns of the said matrix
print(matrix.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [ ]:
# example 2 : using indexing
import numpy as np

matrix = np.array([[4,3,2],[8,7,6]])
rows = matrix.shape[0]
columns = matrix.shape[1]

print("rows:",rows)
print("columns:",columns)

rows: 2
columns: 3


In [ ]:
# select elements from given matrix
# with the help of Numpy as matrix.take() method , we can select elelments from a given
# matrix by passing the parameter as index value of that element. it will return a matrix
# having one dimension. Remember that it will work for one axis at a time

# syntax: matrix.take(index,axis)
# return :return matrix of selected indexes

# example 1
import numpy as np

gf = np.matrix('[4,1,12,3,4,6,7]')

gf1 = np.matrix('[4, 12, 1; 3, 4, 5; 7, 5, 4]')

value = gf.take(2)

value1 = gf.take(0,1)

value2 = gf1.take(0,1)

print(value)

print(value1)

print(value2)

[[12]]
[[4]]
[[4 3 7]]


In [ ]:
# find the sum of values in a matrix
# syntax: matrix.sum()
# return: return sum of values in  matrix
# example 1
import numpy as np
gf = np.matrix('[4,1;12,3]')

sum = gf.sum()

print(sum)

20


In [ ]:
# example 2
import numpy as np
gf = np.matrix('[4,1,9;12,3,4;4,5,6]')
sum = gf.sum(axis = 1)
print(sum)

[[14]
 [19]
 [15]]


In [ ]:
# calculate the sum of diagonal elements of a NumpPy array
# sometimes we have to find the sum of upper right ,lower right and lower left,lower right diagonal elments
# Numpy provides us the facility to compute the sum of different diagonals elments using
# numpy.trace() and numpy.diagonal() method
# method 1 :Finding the sum of elments using numpy.trace()
# syntax: numpyy.trace(a,offset=0,axis1 = 0,axis2 = 1,dype = None ,out = None)
# example 1:For 3x3 Numpy matrix
import numpy as np
n_array = np.array([[44,55,13],
                    [12,67,89],
                    [34,58,75]])
# displaying the matrix
print("Numpy Matrix is:")
print(n_array)

# calculating the trace of a matrix
trace = np.trace(n_array)

print("\nTrace of given 3x3 matrix:")
print(trace)


Numpy Matrix is:
[[44 55 13]
 [12 67 89]
 [34 58 75]]

Trace of given 3x3 matrix:
186


In [ ]:
# exaple 2 :For 4x4 Numpy matrix
import numpy as np
n_array = np.array([[44,55,13,34],
                    [12,67,89,56],
                    [34,58,75,78],
                    [23,14,76,98]])
# displaying the matrix
print("Numpy Matrix is:")
print(n_array)

# calculating the trace of a matrix
trace = np.trace(n_array)

print("\nTrace of given 3x3 matrix:")
print(trace)

Numpy Matrix is:
[[44 55 13 34]
 [12 67 89 56]
 [34 58 75 78]
 [23 14 76 98]]

Trace of given 3x3 matrix:
284


In [ ]:
# Method 2 : Finding the sum of diagonal elements using numpy.diagonal()
# syntax: numpy.diagonal(a,offset=0,axis1 = 0, axis2=1)
# example 1: for 3x3 Numpy Matrix
import numpy as np
n_array = np.array([[44,55,13],
                    [12,67,89],
                    [34,58,75]])

print("Numpy Matrix is:")
print(n_array)
# finding the diagonal elements of matrix
diag = np.diagonal (n_array)

print("\nDiagonal elements are:")
print(diag)

print("\nsum of Diagonal elements is:")
print(np.sum(diag))

Numpy Matrix is:
[[44 55 13]
 [12 67 89]
 [34 58 75]]

Diagonal elements are:
[44 67 75]

sum of Diagonal elements is:
186


In [ ]:
# example2 : For 5x5 Numpy as Matrix
import numpy as np
n_array = np.array([[5, 2, 1, 4, 6],
                    [9, 4, 2, 5, 2],
                    [11, 5, 7, 3, 9],
                    [5, 6, 6, 7, 2],
                    [7, 5, 9, 3, 3]])

print("Numpy Matrix is:")
print(n_array)

diag = np.diagonal(n_array)

print("\nDiagonal elements are:")
print(diag)

print("\nSum of Diagonal elements is:")
print(np.sum(diag))

Numpy Matrix is:
[[ 5  2  1  4  6]
 [ 9  4  2  5  2]
 [11  5  7  3  9]
 [ 5  6  6  7  2]
 [ 7  5  9  3  3]]

Diagonal elements are:
[5 4 7 7 3]

Sum of Diagonal elements is:
26


In [ ]:
# adding and subtracting the matrices in python
# 1,adding elements of the matrix
# np.add() method used to add elements . if the shape of two arrays rae not same
#,that is arr1.shape != arr2.shape ,they must be broard carstable to a common shape
#(which maybe the shape of one or the other)
import numpy as np
A = np.array([[1,2],[3,4]])
B = np.array([[4,5],[6,7]])

print("Printing elements of first matrix")
print(A)

print("Printing the elements of second matrix")
print(B)

# adding the two matrix
print("Addition of two matrix")
print(np.add(A,B))

Printing elements of first matrix
[[1 2]
 [3 4]]
Printing the elements of second matrix
[[4 5]
 [6 7]]
Addition of two matrix
[[ 5  7]
 [ 9 11]]


In [ ]:
# subtracting elements of the matrix
# np.subtract()
# it returns the difference of arr1 and arr2 ,element-wise
import numpy as np
A = np.array([[1,2],[3,4]])
B = np.array([[4,5],[6,7]])

print("Printing elements of first matrix")
print(A)

print("Printing the elements of second matrix")
print(B)

# subtracting the two matrix
print("Addition of two matrix")
print(np.subtract(A,B))

Printing elements of first matrix
[[1 2]
 [3 4]]
Printing the elements of second matrix
[[4 5]
 [6 7]]
Addition of two matrix
[[-3 -3]
 [-3 -3]]


In [ ]:
# method 3 :using nested loops
# it uses the nested loops to print the elemnets of two matrices then subtract the
# corresponding elements of the matrices to get the result matrix
# algorithm :
# 1.Define two matrices 1 and 2
# 2. print the elements of matrix 1 and matrix 2 using the nested loops
# 3. Define an empty matrix result of the same size as matrix1
# 4. Subtract the corresponding elements of matrix 1 and matrix 2 using the nested loops
# and store the result in the result matrix:
# 5.print the result matrix
matrix1 = [[1,2],[3,4]]
matrix2 = [[4,5],[6,7]]

# printing the elements of matrix1
print("Printing elements of first matrix")
for row in matrix1:
  for element in row:
      print(element,end=" ")
  print()


#printing the elements of matrix2
print("Printing elements of second matrix")
for row in matrix2:
  for element in row:
      print(element,end=" ")
  print() # this print is for what?

# subtracting two matrices
result = [[0,0],[0,0]]
for i in range(len(matrix1)):
  for j in range(len(matrix1[0])):
      result[i][j] = matrix1[i][j] - matrix2[i][j]

# printing the result
print("Subtraction of two matrix")
for row in result:
  for elemnet in row:
    print(element,end=" ")
  print()

Printing elements of first matrix
1 2 
3 4 
Printing elements of second matrix
4 5 
6 7 
Subtraction of two matrix
7 7 
7 7 


In [ ]:
matrix1 = [[1, 2], [3, 4]]
matrix2 = [[4, 5], [6, 7]]

# Printing elements of matrix1
print("Printing elements of first matrix")
for row in matrix1:
    for element in row:
        print(element, end=" ")
    print()

# Printing elements of matrix2
print("Printing elements of second matrix")
for row in matrix2:
    for element in row:
        print(element, end=" ")
    print()

# Subtracting two matrices
result = [[0, 0], [0, 0]]
for i in range(len(matrix1)):
    for j in range(len(matrix1[0])):
        result[i][j] = matrix1[i][j] - matrix2[i][j]

# Printing the result
print("Subtraction of two matrix")
for row in result:
    for element in row:
       print(element, end=" ")
    print()

Printing elements of first matrix
1 2 
3 4 
Printing elements of second matrix
4 5 
6 7 
Subtraction of two matrix
-3 -3 
-3 -3 


In [4]:
# ways to add row and columns in numpy array
# Add colmns in the numpy array
# method 1 :Using np.append()
import numpy as np
ini_array = np.array([[1,2,3],[45,4,7],[9,6,10]])

# printing the intial array
print("intial_array:",str(ini_array));

#array to be added as column
column_to_be_added = np.array([[1],[2],[3]])

# Adding column to array using append() method
arr = np.append(ini_array,column_to_be_added,axis = 1)

# printing the result
print("result array ",str(arr))

intial_array: [[ 1  2  3]
 [45  4  7]
 [ 9  6 10]]
result array  [[ 1  2  3  1]
 [45  4  7  2]
 [ 9  6 10  3]]


In [6]:
# method 2 :using concatenate
import numpy as np
ini_array = np.array([[1,2,3],[45,4,7],[9,6,10]])

# printing the intial array
print("intial_array:",str(ini_array));

#array to be added as column
column_to_be_added = np.array([[1],[2],[3]])

# Adding column to array using append() method
arr = np.concatenate([ini_array,column_to_be_added],axis = 1)

# printing the result
print("result array ",str(arr))

intial_array: [[ 1  2  3]
 [45  4  7]
 [ 9  6 10]]
result array  [[ 1  2  3  1]
 [45  4  7  2]
 [ 9  6 10  3]]


In [7]:
#method 3: using insert()
import numpy as np
ini_array = np.array([[1, 2, 3], [45, 4, 7], [9, 6, 10]])

# Array to be added as column
column_to_be_added = np.array([[1], [2], [3]])

# adding column to array using append() method
arr = np.insert(ini_array,0,column_to_be_added,axis=1)

# print the result
print("resultant array:",str(arr))

resultant array: [[ 1  2  3  1  2  3]
 [ 1  2  3 45  4  7]
 [ 1  2  3  9  6 10]]


In [8]:
 # method 4:using np.hstack()
import numpy as np

ini_array = np.array([[1, 2, 3], [45, 4, 7], [9, 6, 10]])

# Array to be added as column
column_to_be_added = np.array([1, 2, 3])

# adding coulmn to numpy array
result = np.hstack((ini_array,np.atleast_2d(column_to_be_added).T))

print("resultant array",str(result))

resultant array [[ 1  2  3  1]
 [45  4  7  2]
 [ 9  6 10  3]]


In [9]:
# method 5 :using np.coulmn_stack()
import numpy as np

ini_array = np.array([[1, 2, 3], [45, 4, 7], [9, 6, 10]])

# Array to be added as column
column_to_be_added = np.array([1, 2, 3])

# Adding column to numpy array
result = np.column_stack((ini_array,column_to_be_added))

print("resultant array:",str(result))

resultant array: [[ 1  2  3  1]
 [45  4  7  2]
 [ 9  6 10  3]]


In [11]:
# ADD ROWS IN NUMPY ARRAY
# method 1 :using np.r_
import numpy as np

ini_array = np.array([[1, 2, 3], [45, 4, 7], [9, 6, 10]])

# printing initial array
print("initial_array : ", str(ini_array));

# array to be added as row
row_to_be_added = np.array([1,2,3])

# adding row to numpy array
result = np.r_[ini_array,[row_to_be_added]]

print("resultant array",str(result))

initial_array :  [[ 1  2  3]
 [45  4  7]
 [ 9  6 10]]
resultant array [[ 1  2  3]
 [45  4  7]
 [ 9  6 10]
 [ 1  2  3]]


In [12]:
# method 2 using np.insert()
import numpy as np

ini_array = np.array([[1, 2, 3], [45, 4, 7], [9, 6, 10]])

# Array to be added as row
row_to_be_added = np.array([1, 2, 3])

#last row
row_n = arr.shape[0]
arr = np.insert(ini_array,row_n,[row_to_be_added],axis= 0)

# printing result
print ("resultant array", str(arr))

resultant array [[ 1  2  3]
 [45  4  7]
 [ 9  6 10]
 [ 1  2  3]]


In [14]:
# method 4: numpy.append()
# example 1:Adding new rows to an empty 2-D array
import numpy as np

# creating the an empty 2d array of int type
empt_array = np.empty((0,2),int)
print("Empty array:")
print(empt_array)

# adding two new rows to empt_array
# using np.append()
empt_array = np.append(empt_array,np.array([[10,20]]),axis = 0)
empt_array = np.append(empt_array,np.array([[40,50]]),axis = 0)

print("\nNow array is:")
print(empt_array)

Empty array:
[]

Now array is:
[[10 20]
 [40 50]]


In [16]:
# Matrix multiplication in NumPY
# IN python numpy.dot() method is used to calculate the dot product between two arrays
# example1 :Matrix Multiplication of 2 square matrices
import numpy as np

# creaing two matrices
p = [[1,2],[2,3]]
q = [[4,5],[6,7]]
print("Matrix p:")
print(p)
print("Matrix q:")
print(q)

# computing product
result = np.dot(p,q)

# printing the result
print("The matrix multiplication is:")
print(result)


Matrix p:
[[1, 2], [2, 3]]
Matrix q:
[[4, 5], [6, 7]]
The matrix multiplication is:
[[16 19]
 [26 31]]


In [ ]:
# Matrix multiplication of rectangular matrix

In [25]:
# get eigen values of a matrix
# method : np.eignvals()
# example 1 :

from numpy import linalg as LA # what is LA?

# using the np.eiganvals() method
gf = LA.eigvals([[1,2],[3,4]])

print(gf)

[-0.37228132  5.37228132]


In [27]:
# example 2:
from numpy import linalg as LA
gf = LA.eigvals([[1,2,3],[4,5,6],[7,8,9]])

print(gf)

[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]


In [28]:
# Calculating the determinant of a matrix using NumPy
# A Special number that can be calculated from a square matrix - Determinant of a square matrix
# syntax: numpy.linalg.det(array)
# example 1: Determinant of 2x2 Numpy matrix
import numpy as np

n_array = np.array([[50,29],[30,44]])

# displaying the matrix
print("Numpy Matrix is:")
print(n_array)

# calculating the determinant of matrix
det = np.linalg.det(n_array)

print("n\Determinant of given 2x2 matrix:")
print(int(det))

Numpy Matrix is:
[[50 29]
 [30 44]]
n\Determinant of given 2x2 matrix:
1330


In [29]:
# Inverse a matrix using numpy
# syntax :numpy.linalg.inv(a)
# parmeters
# a:Matrix to be inverted
# Returns: inverse of matrix
# example 1:
import numpy as np

# taking 3x3 matrix
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])

# calculating the inverse of the matrix
print(np.linalg.inv(A))

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [33]:
# example 2: create multiple numpy array matrices and then convert them in to
# their inverse matrices using np.linalg.inv() function
import numpy as np

# Inverse of several matrices can be computed at once
A = np.array([[[1.,2.],[3.,4.]],
             [[1,3],[3,5]]])

# calculating the inverse of matrix
print(np.linalg.inv(A))

[[[-2.    1.  ]
  [ 1.5  -0.5 ]]

 [[-1.25  0.75]
  [ 0.75 -0.25]]]
