<a href="https://colab.research.google.com/github/ganesh12112/ganesh12112/blob/main/AI_and_ML_assignment_1(NumPy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#assignment on machine learning libraries
# assignments on numpy
# 1.get the max value from matrix
# Syntax : matrix.max()
# return max value from given matrix
# example 1:
import numpy as np
gf = np.matrix('[54, 1; 12, 3]')
max = gf.max()
print(max)

54


In [3]:
# example 2
import numpy as np
gf = np.matrix('[1,2,3; 4,5,6;7,8,9]')
max = gf.max()
print(max)

9


In [5]:
# get the minnimum value of matrix
# example 1
import numpy as np
# make matrix with numpy
gf = np.matrix('[32,45;56,78]')
min = gf.min()
print(min)

32


In [7]:
# Find the number of rows and columns of a given matrix using NumPy
# eaxmple 1:using the .shape Attribute
import numpy as np
matrix = np.array([[9,9,9],[8,8,8]])
dimensions = np.shape(matrix)
rows , columns = dimensions
print("rows:",rows)
print("columns:",columns)

rows: 2
columns: 3


In [9]:
# numpy.reshape() to find number of rows and columns of a matrix
import numpy as np
matrix = np.arange(1,10).reshape((3,3))
# original matrix
print(matrix)
# Number of rows and columns of the said matrix
print(matrix.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [11]:
# example 2 : using indexing
import numpy as np

matrix = np.array([[4,3,2],[8,7,6]])
rows = matrix.shape[0]
columns = matrix.shape[1]

print("rows:",rows)
print("columns:",columns)

rows: 2
columns: 3


In [23]:
# select elements from given matrix
# with the help of Numpy as matrix.take() method , we can select elelments from a given
# matrix by passing the parameter as index value of that element. it will return a matrix
# having one dimension. Remember that it will work for one axis at a time

# syntax: matrix.take(index,axis)
# return :return matrix of selected indexes

# example 1
import numpy as np

gf = np.matrix('[4,1,12,3,4,6,7]')

gf1 = np.matrix('[4, 12, 1; 3, 4, 5; 7, 5, 4]')

value = gf.take(2)

value1 = gf.take(0,1)

value2 = gf1.take(0,1)

print(value)

print(value1)

print(value2)

[[12]]
[[4]]
[[4 3 7]]


In [24]:
# find the sum of values in a matrix
# syntax: matrix.sum()
# return: return sum of values in  matrix
# example 1
import numpy as np
gf = np.matrix('[4,1;12,3]')

sum = gf.sum()

print(sum)

20


In [25]:
# example 2
import numpy as np
gf = np.matrix('[4,1,9;12,3,4;4,5,6]')
sum = gf.sum(axis = 1)
print(sum)

[[14]
 [19]
 [15]]


In [26]:
# calculate the sum of diagonal elements of a NumpPy array
# sometimes we have to find the sum of upper right ,lower right and lower left,lower right diagonal elments
# Numpy provides us the facility to compute the sum of different diagonals elments using
# numpy.trace() and numpy.diagonal() method
# method 1 :Finding the sum of elments using numpy.trace()
# syntax: numpyy.trace(a,offset=0,axis1 = 0,axis2 = 1,dype = None ,out = None)
# example 1:For 3x3 Numpy matrix
import numpy as np
n_array = np.array([[44,55,13],
                    [12,67,89],
                    [34,58,75]])
# displaying the matrix
print("Numpy Matrix is:")
print(n_array)

# calculating the trace of a matrix
trace = np.trace(n_array)

print("\nTrace of given 3x3 matrix:")
print(trace)


Numpy Matrix is:
[[44 55 13]
 [12 67 89]
 [34 58 75]]

Trace of given 3x3 matrix:
186


In [28]:
# exaple 2 :For 4x4 Numpy matrix
import numpy as np
n_array = np.array([[44,55,13,34],
                    [12,67,89,56],
                    [34,58,75,78],
                    [23,14,76,98]])
# displaying the matrix
print("Numpy Matrix is:")
print(n_array)

# calculating the trace of a matrix
trace = np.trace(n_array)

print("\nTrace of given 3x3 matrix:")
print(trace)

Numpy Matrix is:
[[44 55 13 34]
 [12 67 89 56]
 [34 58 75 78]
 [23 14 76 98]]

Trace of given 3x3 matrix:
284


In [36]:
# Method 2 : Finding the sum of diagonal elements using numpy.diagonal()
# syntax: numpy.diagonal(a,offset=0,axis1 = 0, axis2=1)
# example 1: for 3x3 Numpy Matrix
import numpy as np
n_array = np.array([[44,55,13],
                    [12,67,89],
                    [34,58,75]])

print("Numpy Matrix is:")
print(n_array)
# finding the diagonal elements of matrix
diag = np.diagonal (n_array)

print("\nDiagonal elements are:")
print(diag)

print("\nsum of Diagonal elements is:")
print(np.sum(diag))

Numpy Matrix is:
[[44 55 13]
 [12 67 89]
 [34 58 75]]

Diagonal elements are:
[44 67 75]

sum of Diagonal elements is:
186


In [37]:
# example2 : For 5x5 Numpy as Matrix
import numpy as np
n_array = np.array([[5, 2, 1, 4, 6],
                    [9, 4, 2, 5, 2],
                    [11, 5, 7, 3, 9],
                    [5, 6, 6, 7, 2],
                    [7, 5, 9, 3, 3]])

print("Numpy Matrix is:")
print(n_array)

diag = np.diagonal(n_array)

print("\nDiagonal elements are:")
print(diag)

print("\nSum of Diagonal elements is:")
print(np.sum(diag))

Numpy Matrix is:
[[ 5  2  1  4  6]
 [ 9  4  2  5  2]
 [11  5  7  3  9]
 [ 5  6  6  7  2]
 [ 7  5  9  3  3]]

Diagonal elements are:
[5 4 7 7 3]

Sum of Diagonal elements is:
26
