<a href="https://colab.research.google.com/github/ganesh12112/ganesh12112/blob/main/AI_and_Ml_22_10_23.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# Numpy
# why Numpy ?  takes an object return c type array!
import time

li = [i for i in range(100000)]

starttime =  time.process_time()

li = [i*2 for i in li]

endtime = time.process_time()

print(endtime-starttime)

0.016226214000000017


In [7]:
import numpy as np
import time

nparr = np.array([i for i in range(100000)])

starttime =  time.process_time()

#for i in range(1000000):
  #nparr[i] = nparr[i] *2
nparr *= 2 # performs *@ operation fo every ele in nparr
endtime = time.process_time()

print(endtime-starttime)

0.0006501910000000777


In [6]:
def fun(firstname = 'Ganesh',lastname='chowdary'):
    print("welcome",firstname,lastname)

fun("are","gani")

welcome are gani


In [8]:
marklist = [60,79,88,95,57,84]
markarray = np.array(marklist)
print(type(marklist))
print(type(markarray))

<class 'list'>
<class 'numpy.ndarray'>


In [9]:
markarray = np.array(marklist,dtype=np.int8)
print(markarray.dtype)

int8


In [16]:
import numpy as np
temp = np.array([16,8,10,3,16,12,9,6,7])
print(temp)
temp1 = temp.reshape(3,3)
print(temp1.shape)
print(temp1[0][1])

[16  8 10  3 16 12  9  6  7]
(3, 3)
8


In [18]:
temp2 = np.reshape(temp,(-1,1)) #-1 indicates rows will not change
print(temp)
print(temp.shape)

[16  8 10  3 16 12  9  6  7]
(9,)


In [23]:
li = [ i for i in range(1,26)]
print(li)

array = np.array([ i for i in range(1,26)])
print(array.reshape(5,5))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [38]:
array = array%2 == 0
array
print(array)
for i in range(0,4):
  for j in range(0,4):
      if array[i][j] == True:
          array[i] = "Even"
      else:
          array[i][j] = "odd"

[ True False False False False False False False False False False False
 False False False False False False False False False False False False
 False]


IndexError: ignored

In [45]:
import numpy.random as rd
rndobj = rd.default_rng(seed = 10) # seed - reference values
rndobj.standard_normal(5)

array([-1.10333845, -0.72502464, -0.78180526,  0.26697586, -0.24858073])

In [42]:
li = [ i for i in range (1,26)]
matrix = np.array(li)
print(matrix.reshape(5,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
# IQR = Q3-Q2
# 1.5(IQR) + Q3
# almost every data follows normal distribution curve any mean value and sd also any
# standard normal curve - mean = 0 and standard deviation = 1
# z score = x-mu/
# poissons and binomial

In [ ]:
# pandas
# video games sales
#panda - panel Data Tabular-XLS, XLSX ,RDBMS ,CSV
# -read,wrangle,clean,replace,merge
# what is data wrangling
# datatypes - series and dataframe

In [ ]:
series =

In [48]:
import pandas as pd
temp = {'Date':['22-10-23','23-10-23'],
        'MinTemp':[7,11],
        'Maxtemp':[23,18]}

temp_df = pd.DataFrame(temp)
print(temp_df)

print(temp_df['MinTemp'][0])

       Date  MinTemp  Maxtemp
0  22-10-23        7       23
1  23-10-23       11       18
7


In [53]:
# load or read the file in pandas
vsd = pd.read_excel('/content/vgsales.xlsx')

In [54]:
print(vsd.shape)

(16598, 11)


In [56]:
vsd.show

AttributeError: ignored