<a href="https://colab.research.google.com/github/ganesh12112/ganesh12112/blob/main/session9_AI_and_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# NUMPY AND STATISTICS
#1.NUMPY
#2.CREATION
#3. INDEXING
#4.SLICING
#5.ATTRIBUTES
#6.STATISTICS

In [1]:
# CREATION OF ARRAYS
import numpy as np
A = np.array([[1,2,3],[4,5,6]])
B = np.empty([2,2])
C = np.zeros([3,3])
D = np.ones([4,4])
print("array A:")
print(A)
print("array B:")
print(B)
print("array C:")
print(C)
print("array D:")
print(D)

array A:
[[1 2 3]
 [4 5 6]]
array B:
[[4.78046723e-310 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]
array C:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
array D:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [4]:
import numpy as np
l = "hello string" # converting list,tuple,string
A = np.asarray(l)
print(A)

hello string


In [5]:
# array with arange function
a = np.arange(13)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]


In [18]:
# attributes of the array
import numpy as np
A = np.array([[1,2,3],[4,5,6]])
print(A.shape)
print(A.ndim)
print(A.itemsize)
print(A.reshape(3,2))

(2, 3)
2
8
[[1 2]
 [3 4]
 [5 6]]


In [24]:
# indexing and slicing operations on array
print(A[:,[1]]) #
print(A[0,1]) # acess the 2nd element in the first row
print(A[:,0:3])
print(A[1,:])
B = A[0,:]
C = A[1,:]
print('B=',B )

S = 0
for X in B:
  S = S+X
print('sum = ',S)


[[2]
 [5]]
2
[[1 2 3]
 [4 5 6]]
[4 5 6]
B= [1 2 3]
sum =  6


In [25]:
# HOW TO STORE ROWS, CLOUMNS
A = np.array([[1,2,3],[4,5,6]])
r,c = A.shape
print('rows=',r)
print('columns=',c)

for x in A:
  for y in x:
    print(y)


rows= 2
columns= 3
1
2
3
4
5
6


In [41]:
# assignment 1 - create a 3*3 matrix print the sum of each column
# assigmnet 2 - count no of zeros and print

A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = A[:,0]
C = A[:,1]
D = A[:,2]

print('B=',B )
print('C=',C )
print('D=',D )

for i in range(3):
  column_sum = 0
  for j in range(3):
    column_sum += A[j][i]
  print(column_sum)
zeros = np.count_nonzero(A == 0,axis =0)
print(zeros)

B= [1 4 7]
C= [2 5 8]
D= [3 6 9]
12
15
18
[0 0 0]


In [47]:
# Arithematic operations
import numpy as np
A = np.array([[11,20,30],[25,38,60]])
B = np.array([2,1,2])

print(A)
print(B)

print(np.add(A,B))

[[11 20 30]
 [25 38 60]]
[2 1 2]
[[13 21 32]
 [27 39 62]]


In [44]:
print(np.subtract(A,B))

[[ 8 19 28]
 [38 49 58]]


In [45]:
print(np.multiply(A,B))

[[ 20  20  60]
 [ 80  50 120]]


In [48]:
print(np.mod(A,B))

[[1 0 0]
 [1 0 0]]


In [49]:
print(np.power(A,B))

[[ 121   20  900]
 [ 625   38 3600]]


In [64]:
# statistics with numpy
A = np.array([[11,20,30],[25,38,60]])
print(A)

print(np.amin(A,1)) # MIN VALUE AXIS = 0 IT WILL WORK ON COLUMN
print(np.amax(A,1))

print(np.median(A,0))
print(np.mean(A,0))
print(np.std(A,0))


[[11 20 30]
 [25 38 60]]
[11 25]
[30 60]
[18. 29. 45.]
[18. 29. 45.]
[ 7.  9. 15.]


In [73]:
# create 4*4 matrix and compute the statistics of all rows and columns and print
import numpy as np
import scipy.stats as stats
#A = np.array([[1,2,3],[4,5,6],[7,8,9],[4,6,8]])
#print(A)

A = np.array([[6,8,5,2],[6,2,8,1],[7,2,1,6],[8,5,2,3]])
print("matrix is:")

print(A)

# COMPUTE THE statistics of all rows
#row_stats = stats.describe(A ,axis = 1)
#print("statistics of all rows are:")
#print(row_stats)


# COMPUTE THE statistics of all columns
#column_stats = stats.describe(A ,axis = 0)
#print("statistics of all rows are:")
#print(column_stats)

print(np.amin(A,0))
print(np.amax(A,0))

print(np.median(A,0))
print(np.mean(A,0))
print(np.std(A,0))


matrix is:
[[6 8 5 2]
 [6 2 8 1]
 [7 2 1 6]
 [8 5 2 3]]
[6 2 1 1]
[8 8 8 6]
[6.5 3.5 3.5 2.5]
[6.75 4.25 4.   3.  ]
[0.8291562  2.48746859 2.73861279 1.87082869]


In [8]:
# SORTING THE elements in an array
import numpy as np
A = np.array([[1,2,3],[10,20,-9],[8,6,7]])
B = np.array([['bxy'],['axy'],['xxy']])
print("original array")
print(A)
print("sorted array")
print(np.sort(A,0))
print(np.sort(B,0))

original array
[[ 1  2  3]
 [10 20 -9]
 [ 8  6  7]]
sorted array
[[ 1  2 -9]
 [ 8  6  3]
 [10 20  7]]
[['axy']
 ['bxy']
 ['xxy']]


In [13]:
# searching operations
A = np.array([[1,2,3],[10,20,-9],[8,6,7]])
print(A)
y = np.where(A>5)
print("Indices")
print(y)
print("values")
print(A[y])

[[ 1  2  3]
 [10 20 -9]
 [ 8  6  7]]
Indices
(array([1, 1, 2, 2, 2]), array([0, 1, 0, 1, 2]))
values
[10 20  8  6  7]


In [18]:
# assisnment matrix function with arange function , find the elemnts >6 and sum of all elements
A = np.arange(16).reshape((4,4))
print(A)
y = np.where(A>6)
print("Indices")
print(y)
print("values")
print(A[y])

sum = np.sum(A)
print(sum)

# another method with for loop
sum = 0
for row in A:
  for element in row:
    sum += element
# print the sum
print(sum)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Indices
(array([1, 2, 2, 2, 2, 3, 3, 3, 3]), array([3, 0, 1, 2, 3, 0, 1, 2, 3]))
values
[ 7  8  9 10 11 12 13 14 15]
120
120
