<a href="https://colab.research.google.com/github/ganesh12112/ganesh12112/blob/main/session_4_ai_and_ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# session 4
#tuples,dictionaries,dataframes(numpy and pandas)
tuple = (10,12,23,'a','b') # thes are immutable
list = [1,3,4,5,6] # mutable
#tuple[0] = 56
list[0] = 45
print(tuple)
print(list)

(10, 12, 23, 'a', 'b')
[45, 3, 4, 5, 6]


In [ ]:
# concatenation of number
t1 = (1,2,3,4,5)
t2 = (45,6,78,34)
print(t1+t2)
print(len(t1)) # lenth of tuple1
print(t1*2) # repetition of tuple 1
print(12 in t1)
# using for lopp to acess every element in tuple1
for i in t1:
  print(i)

(1, 2, 3, 4, 5, 45, 6, 78, 34)
5
(1, 2, 3, 4, 5, 1, 2, 3, 4, 5)
False
1
2
3
4
5


In [ ]:
# dictionaries - set of items with "key-value pair" enclosed in { }.
dict1 = {'a':100,'b':200,'c':300} # a = key ,100= value like that
print(dict1)
# we can acess the value by keys in the dictionary
print(dict1['a'])
print(dict1.keys())
print(dict1.values())
# use for loop to find the values of key
i = 0
for score in dict1.values():
  i = i+score
print(i/len(dict1))
# why we intialize i = 0 or any varible in loops(for)
# solution  we are not printing the list of items in a dictionarie i.e
# performing the operation called calculation of average
# rsfer some more examples to get clarity on this

{'a': 100, 'b': 200, 'c': 300}
100
dict_keys(['a', 'b', 'c'])
dict_values([100, 200, 300])
200.0


In [ ]:
# numpy data struture - numerical python librarary
# it contains all the neccessary routines that operate on array
# we can various array objects 1d, 2d and multi dimensional
# it providesset tof routines to operate on all array objects
# import numpy
import numpy as np
A = np.array([1,2,3,4,5]) # creating an array 1d
B = np.array([[1,2,3],[4,5,6]]) # creating an 2d array
print(A)
print(B)
print(A.shape) # gives the no of rows and columns
print(B.shape)
# acessinng the individual elements
print(B[0,0]) # Acessing the first element of array i.e it is 2d array
print(B[0,1]) # second element


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
(5,)
(2, 3)
1
2


In [ ]:
# assignment 1 = create 2d array ,find sum of all elments
import numpy as np
A = np.array([[1,2,3],[4,5,6]])
r,c = B.shape # r= rows,c= columns
s=0
for i in range(0,r):
  for j in range(0,c):
    s = s+B[i,j]
print("sum=",s)
# assigment 2 = sum of each row and sum of each column
# each row
import numpy as np
A = np.array([[1,2,3],[4,5,6]])
r,c = B.shape # r= rows,c= columns
print(A)
print(np.sum(B,axis = 1))
print(np.sum(B,axis = 0))

sum= 21
[[1 2 3]
 [4 5 6]]
[ 6 15]
[5 7 9]


In [ ]:
# finding the sum of each row and column by the for loop
import numpy as np
A = np.array([[1,2,3],[4,5,6]])
for i in range(0,r):
  s = 0
  for j in range(0,c):
      s = s+A[i,j]
  print("sum of rows=",i,"is=",s)

# what is the differnce between intialize a varible outside the loop and inside the loop

sum of rows= 0 is= 6
sum of rows= 1 is= 15


In [42]:
# Another way to find sum  of each row
import numpy as np
A = np.array([[1,2,3],[4,5,6]])
B = A.shape
print("rows=", r)
print("col=", c)
s = 0
for i in range(0,r):
  for j in range(0,c):
    s = s+A[i,j]
print(s)

rows= 2
col= 3
21


In [ ]:
# finding the  sum of each column
import numpy as np
A = np.array([[1,2,3],[4,5,6]])
for i in range(0,c): # interchange row with column
  s = 0
  for j in range(0,r):
      s = s+A[j,i]   # here also
  print("sum of columns=",i,"is=",s)

sum of columns= 0 is= 5
sum of columns= 1 is= 7
sum of columns= 2 is= 9


In [46]:
# methods avalilable in numpy
# add,subtract,multiply,divide,sum ,std ,average
A = np.array([[0,2,2],[4,7,8]])
B = np.array([[1,2,3],[4,5,6]])
print(np.add(A,B))
print(np.subtract(A,B))
print(np.multiply(A,B))
print(np.divide(A,B))


[[ 1  4  5]
 [ 8 12 14]]
[[-1  0 -1]
 [ 0  2  2]]
[[ 0  4  6]
 [16 35 48]]
[[0.         1.         0.66666667]
 [1.         1.4        1.33333333]]


In [51]:
# create sparse matrix and count number of zeros in the matrix
import numpy as np
from scipy.sparse import csr_matrix
A = np.array([[1,2,3,0,0],[0,0,4,5,6],[0,0,0,1,1],[2,3,4,5,0]])
B = A.shape
print(B)
sparseMatrix = csr_matrix((4,5),dtype = np.int8).toarray()
print(sparseMatrix)

(4, 5)
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [60]:
# another way to create
import numpy as np
A = np.array([[1,2,3,0,0],[0,0,4,5,6],[0,0,0,1,1],[2,3,4,5,0]])
r,c = A.shape
s = 0
for i in range(0,r):
   for j in range(0,c):
     if A[i,j] == 0:
       s = s+1
print("Zeroes count=",s)

Zeroes count= 8


In [64]:
# pandas - data analysis package
# datatypes - series ,dataframe and panel
#series - 1d object creation
#dataframe - tabular form of data
# panel - 3d data representation(images,video analysis)
# lets start with series data type
import pandas as pd
S = pd.Series([10,20,30,40])
print(S)
# WE CAN ASLO GIVE THE INDEX VALUES to our series manually
S1 = pd.Series([10,20,30,40],index =[1,2,3,4])
print(S1)
print(S1[1])

0    10
1    20
2    30
3    40
dtype: int64
1    10
2    20
3    30
4    40
dtype: int64
10


In [69]:
# dataframe object
import pandas as pd
D = pd.DataFrame([['a',10],['b',20],['c',12],['d',13]],columns =['name','age'])
print(D)

  name  age
0    a   10
1    b   20
2    c   12
3    d   13


In [74]:
# we can also create dataframe from dictionary
import pandas as pd
D = pd.DataFrame([{'mmk':20,'sss':34}])
print(D)

   mmk  sss
0   20   34


In [76]:
import pandas as pd
D = {"name":['x','y','z'],'age':[10,20,30],'ratings':[4.3,5.3,6.3]}
P = pd.DataFrame(D)
print(P.describe())

        age  ratings
count   3.0      3.0
mean   20.0      5.3
std    10.0      1.0
min    10.0      4.3
25%    15.0      4.8
50%    20.0      5.3
75%    25.0      5.8
max    30.0      6.3
