<a href="https://colab.research.google.com/github/ganesh12112/ganesh12112/blob/main/session_5_ai_and_ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
# Machine learning
# sk learn ml
# load the data set Iris
from sklearn.datasets import load_iris
iris = load_iris()
X = iris.data
Y = iris.target
features = iris.feature_names
targets = iris.target_names
print(iris.feature_names)
print(iris.target_names)
print(Y)
print("\n First 10 rows of X:\n",X[:10])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]

 First 10 rows of X:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


In [9]:
# splitting the dataset
# to check accuracy of model we can split the dataset in two training and testing set
# assumption 7:3 train to test split
from sklearn.datasets import load_iris
iris = load_iris()
x = iris.data
y = iris.target

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state = 1)
print(x.shape)
print(x_train.shape)
print(y.shape)
print(y_train.shape)

(150, 4)
(105, 4)
(150,)
(105,)


In [14]:
# train the model
# SCIKIT(machine leraning libraray in python) learn has wide range of Machine learning algorithms which have consisitent interface for fitting,predicting accuracy,recall etc
# K- NEAREST NIEGHBOUR ALGORITHM - 1ST MODEL IN DISCCUSSION
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

# loaded the dataset
iris = load_iris()
x = iris.data
y = iris.target
features = iris.feature_names
targets = iris.target_names

#split into tarining and training samples
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size =0.3,random_state=1)

# train the model
knnc = KNeighborsClassifier(n_neighbors=3)
knnc.fit(x_train,y_train) # use of fit?
knnc.predict(x_test)

#tested the model
sample_class = knnc.predict(x_test[0:45,:])
print(x_test[0])
print(x_test[1])
print(sample_class)
# here how we are dividing the data in to classes?????
# does split of data into test and train always random or in a sequence
# for example 10 samples 7:3 ratio 7 as train and 3 as test

# accuracy of the model
acc = metrics.accuracy_score(sample_class,y_test)
print("accuracy=",acc)


[5.8 4.  1.2 0.2]
[5.1 2.5 3.  1.1]
[0 1 1 0 2 1 2 0 0 2 1 0 2 1 1 0 1 1 0 0 1 1 1 0 2 1 0 0 1 2 1 2 1 2 2 0 1
 0 1 2 2 0 1 2 1]
accuracy= 0.9777777777777777


In [21]:
#assignmentt ------- by bt creating own numpy array of glass hieght and width
#from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
import numpy as np

x = np.array([[1,0.3],[1.2,0.4],[1,0.6],[2,0.7],[3,0.3],[2,0.2],[4,1.2],[1,0.2],[2,0.6],[5,0.9],\
[0.02,2],[0.03,3],[0.01,2],[0.05,3],[0.01,2],[0.02,3],[0.01,2],[0.05,3],[0.03,2],[0.04,3]])
y =np.array([0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1])

#split into tarining and training samples
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size =0.3,random_state=1)

# train the model
knnc = KNeighborsClassifier(n_neighbors=3)
knnc.fit(x_train,y_train) # use of fit?
knnc.predict(x_test)

#tested the model
sample_class = knnc.predict(x_test[0:5,:])
print(x_test[0])
print(x_test[1])
print(sample_class)

# accuracy of the model
#acc = metrics.accuracy_score(sample_class,y_test)
#print("accuracy=",acc)

[2.  0.7]
[0.01 2.  ]
[0 1 0 1 0]
